def build_system_prompt() -> str:
    return (
        "Ты — обучающий ассистент.\n"
        "Верни СТРОГО валидный JSON следующей структуры:\n\n"
        "{\n"
        "  \"lesson\": {\n"
        "    \"title\": \"Заголовок\",\n"
        "    \"sections\": [\n"
        "      {\n"
        "        \"header\": \"Подзаголовок\",\n"
        "        \"text\": \"Объяснение простым языком\",\n"
        "        \"key_points\": [\"ключевая идея\"],\n"
        "        \"formula\": \"формула (если есть)\"\n"
        "      }\n"
        "    ]\n"
        "  },\n"
        "  \"cards\": [\n"
        "    {\"question\": \"...\", \"answer\": \"...\"}\n"
        "  ],\n"
        "  \"tests\": [\n"
        "    {\n"
        "      \"question\": \"...\",\n"
        "      \"options\": [\"A\", \"B\", \"C\", \"D\"]\n"
        "    }\n"
        "  ],\n"
        "  \"practice\": {\n"
        "    \"problem\": \"...\",\n"
        "    \"solution\": \"...\"\n"
        "  }\n"
        "}\n\n"
        "Требования:\n"
        "- cards: ровно 5\n"
        "- tests: ровно 5, options всегда 4\n"
        "- язык ответа = язык темы\n"
        "- никакого текста вне JSON"
    )

def build_user_prompt(topic: str) -> str:
    return f"Тема: {topic}"
